### ISSUE TITLE
Crashing RetroPie

### ISSUE THREAD

**Issue by hobgoblina** [c64-dev/es-epicnoir#3]
I had this theme installed and running a month ago, but suddenly it stopped working and I'm getting this issue when running the `emulationstation --debug` script:

```
RetroPie-Setup/tmp/build/emulationstation/es-core/src/resources/Font.cpp:410: void Font::renderTextCache(TextCache*): Assertion `*it->textureIdPtr != 0' failed.
Aborted (core dumped)
```

Not happening with any other themes tho. Not sure what it's indicating is the issue I'm having with your theme, tho.

**Comment by c64-dev** [comment]
The debugging info is indicating that emulationstation is crashing due to a font rendering problem. It could be any number of things. The theme is using it's own fonts which are included in the theme package, so they shouldn't be a problem. 

I would suggest trying other ES themes that use their own fonts to see if the issue persists. 
If it does, then you can do a complete uninstall and reinstall of the emulationstation and subsequently reinstall the epicnoir theme.

I'm closing this issue for now due to no further activity.
