### ISSUE TITLE
Navigation indicator not moving when selecting different systems

### ISSUE THREAD

**Issue by soulrider911** [c64-dev/es-epicnoir#4]
Hi, there I just installed your amazing theme on a build I am working on. What wonderful work, such a great theme. The only issue I am finding is the left-hand navigation is not indexing ( moving ) when different systems are selected. I am running a Raspberry Pi 3B+ and Retropie 4.7.1 Thank you so much!
![pic](https://user-images.githubusercontent.com/1074696/101724200-d8985500-3a62-11eb-8d63-9f597e0fd8fb.png)

**Comment by wiauxb** [comment]
Hi soulrider,

I dont know if there is a cleaner way to fix this issue but here is my workaround:
 - Go to es-epicnoir/_art/indicators/ (`cd ~/.emulationstation/themes/es-epicnoir/_art/indicators/` in the console)
 - rename "1st-system.png" as your first system (systems are listed in alphabetical order) (to rename in console I use `mv old_name new_name`)
 - the same for the 2nd, 3rd, etc.

The down side is that you need to redo this if you add a new system ... but that doesn't often happen ... does it?

**Comment by soulrider911** [comment]
Awesome thank you!!
Brady

**Comment by c64-dev** [comment]
The solution offered by wiauxb is actually the recommended approach. Unfortunately, due to a limitation of emulationstation itself, the navigation indicator cannot be made to move down automatically in accordance to the number of systems a user may have available. 
As such, the only approach is to manually number your systems as above. 

Marking this solved and closed.
