### ISSUE TITLE
ZX81

### ISSUE THREAD

**Issue by fizgog** [c64-dev/es-epicnoir#5]
Hi,

Great work, but I noticed for the ZX81 system you are using a ZX Spectrum image in the controller folder instead of one like this
![zx81_1](https://user-images.githubusercontent.com/25318744/108088919-e96fd300-7070-11eb-9384-f5217de6eaa0.jpg)

**Comment by c64-dev** [comment]
Hi, 

One of the best things about ES themes is that they are open-ended, alowing users to add (or remove) their own systems as they see fit. As such, we couldn't realistically account for all the available consoles and home systems out there, so for a few of them we had to go with the closest available high quality image (in this case the ZX Spectrum image file).

To solve your issue locally, you can easily change a system's image to whatever you want by going to the relevant directory (is this case `_art/controllers/` ) and overwrite the .png image file to the new one, keeping the filename as is.

However, as any changes on my part would effect all users of the EpicNoir theme, I will have to leave the ZX81 system png as is for now, because the image above is not following the top-down aspect and high quality rendering of all the other systems in the theme. 
If you find a ZX81 image which conforms to the above style guidelines, then I will gladly replace the image to the new one.
